// Realistic cinematic Earth: NASA/Three.js Earth texture + custom day/night, city lights, procedural cloud layer, subtle atmosphere, ISS SGP4 overlays.
(async()=>{
const T=await import('https://esm.sh/three@0.180.0');
let sunHelper=null;try{sunHelper=(await import('https://esm.sh/@takram/three-atmosphere@0.19.1?deps=three@0.180.0')).getSunDirectionECEF}catch(e){console.warn('Takram atmosphere helper unavailable; using solar fallback.',e)}
const canvas=document.getElementById('earth3d'),r=new T.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});r.setPixelRatio(Math.min(devicePixelRatio,2));r.setSize(innerWidth,innerHeight);r.outputColorSpace=T.SRGBColorSpace;r.toneMapping=T.ACESFilmicToneMapping;r.toneMappingExposure=1.08;
const s=new T.Scene();s.background=new T.Color(0x02070d);const cam=new T.PerspectiveCamera(38,innerWidth/innerHeight,.01,1000);const rig=new T.Group();s.add(rig);
const sg=new T.BufferGeometry(),a=[];for(let i=0;i<2200;i++){const R=65,u=Math.random()*2-1,q=Math.sqrt(1-u*u),p=Math.random()*Math.PI*2;a.push(R*q*Math.cos(p),R*u,R*q*Math.sin(p))}sg.setAttribute('position',new T.Float32BufferAttribute(a,3));s.add(new T.Points(sg,new T.PointsMaterial({color:0xdff7ff,size:.055,sizeAttenuation:true,transparent:true,opacity:.68})));
const L=new T.TextureLoader();
const earthTex=L.load('https://threejs.org/examples/textures/planets/earth_atmos_2048.jpg');
const normal=L.load('https://threejs.org/examples/textures/planets/earth_normal_2048.jpg');
const spec=L.load('https://threejs.org/examples/textures/planets/earth_specular_2048.jpg');
const lights=L.load('https://threejs.org/examples/textures/planets/earth_lights_2048.png');
[earthTex,lights].forEach(x=>{x.colorSpace=T.SRGBColorSpace;x.anisotropy=r.capabilities.getMaxAnisotropy()});
const sunDir=new T.Vector3(.7,.3,.6).normalize(),E=new T.SphereGeometry(1,192,128);
const em=new T.ShaderMaterial({uniforms:{map:{value:earthTex},normalMap:{value:normal},specMap:{value:spec},lights:{value:lights},sunDir:{value:sunDir}},vertexShader:`varying vec2 vUv;varying vec3 vN;varying vec3 vP;void main(){vUv=uv;vN=normalize(mat3(modelMatrix)*normal);vec4 p=modelMatrix*vec4(position,1.);vP=p.xyz;gl_Position=projectionMatrix*viewMatrix*p;}`,fragmentShader:`uniform sampler2D map,normalMap,lights,specMap;uniform vec3 sunDir;varying vec2 vUv;varying vec3 vN,vP;void main(){vec3 base=texture2D(map,vUv).rgb;vec3 n=normalize(vN);vec3 v=normalize(cameraPosition-vP);float d=dot(n,sunDir);float day=smoothstep(-.07,.2,d);float night=1.-day;vec3 city=texture2D(lights,vUv).rgb*night*1.12;float sp=texture2D(specMap,vUv).r;vec3 h=normalize(sunDir+v);float hi=pow(max(dot(n,h),0.),52.)*sp*.13*max(d,0.);float rim=pow(1.-max(dot(n,v),0.),3.7);vec3 c=base*(.28+.9*day)+city+vec3(hi);c+=vec3(.025,.13,.38)*rim*.08;gl_FragColor=vec4(c,1.);}`});
const earth=new T.Mesh(E,em);earth.position.y=-.06;rig.add(earth);
// Procedural moving cloud layer — no fragile external cloud asset required.
const cm=new T.ShaderMaterial({transparent:true,depthWrite:false,side:T.DoubleSide,uniforms:{sunDir:{value:sunDir},time:{value:0}},vertexShader:`varying vec3 vN;varying vec3 vP;void main(){vN=normalize(mat3(modelMatrix)*normal);vec4 p=modelMatrix*vec4(position,1.);vP=p.xyz;gl_Position=projectionMatrix*viewMatrix*p;}`,fragmentShader:`uniform vec3 sunDir;uniform float time;varying vec3 vN,vP;float hash21(vec2 p){p=fract(p*vec2(123.34,456.21));p+=dot(p,p+45.32);return fract(p.x*p.y);}float noise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);float a=hash21(i),b=hash21(i+vec2(1,0)),c=hash21(i+vec2(0,1)),d=hash21(i+vec2(1,1));return mix(mix(a,b,f.x),mix(c,d,f.x),f.y);}void main(){vec3 n=normalize(vN);float lon=atan(n.z,n.x),lat=asin(clamp(n.y,-1.,1.));vec2 uv=vec2(lon/6.2831853+.5,lat/3.1415926+.5);uv.x=fract(uv.x+time*.000025);float q=noise(uv*7.)*.62+noise(uv*15.)*.25+noise(uv*30.)*.13;float mask=smoothstep(.56,.68,q);float sun=max(dot(n,normalize(sunDir)),0.);float alpha=mask*(.10+.48*sun);gl_FragColor=vec4(vec3(.97,.99,1.),alpha);}`});
const clouds=new T.Mesh(new T.SphereGeometry(1.012,160,112),cm);clouds.position.y=-.06;rig.add(clouds);
const am=new T.ShaderMaterial({transparent:true,side:T.BackSide,depthWrite:false,blending:T.AdditiveBlending,vertexShader:`varying vec3 nW,vW;void main(){nW=normalize(mat3(modelMatrix)*normal);vec4 p=modelMatrix*vec4(position,1.);vW=normalize(cameraPosition-p.xyz);gl_Position=projectionMatrix*viewMatrix*p;}`,fragmentShader:`varying vec3 nW,vW;void main(){float rim=pow(1.-max(dot(nW,vW),0.),4.7);gl_FragColor=vec4(.08,.38,.95,rim*.16);}`});const atmo=new T.Mesh(new T.SphereGeometry(1.038,144,96),am);atmo.position.y=-.06;rig.add(atmo);
const orbit=new T.Line(new T.BufferGeometry(),new T.LineBasicMaterial({color:0x65eaff,transparent:true,opacity:.2}));rig.add(orbit);const iss=new T.Mesh(new T.SphereGeometry(.018,16,16),new T.MeshBasicMaterial({color:0x7af0ff}));rig.add(iss);const halo=new T.Sprite(new T.SpriteMaterial({color:0x7af0ff,transparent:true,opacity:.85,blending:T.AdditiveBlending}));halo.scale.set(.085,.085,1);rig.add(halo);
const sl=new T.DirectionalLight(0xffffff,2.15);s.add(sl);s.add(new T.AmbientLight(0x607586,.45));let auto=true,follow=false,drag=false,x0=0,y0=0,zoom=3.05;
const xyz=(la,lo,rr=1)=>{la*=Math.PI/180;lo*=Math.PI/180;return new T.Vector3(rr*Math.cos(la)*Math.cos(lo),rr*Math.sin(la),-rr*Math.cos(la)*Math.sin(lo))};
function sf(d){const jd=d.getTime()/864e5+2440587.5,n=jd-2451545,L=(280.46+.9856474*n)*Math.PI/180,g=(357.53+.9856*n)*Math.PI/180,lam=L+(1.915*Math.sin(g)+.02*Math.sin(2*g))*Math.PI/180,e=(23.439-.0000004*n)*Math.PI/180,ra=Math.atan2(Math.cos(e)*Math.sin(lam),Math.cos(lam)),dec=Math.asin(Math.sin(e)*Math.sin(lam)),gm=(280.46061837+360.98564736629*n)*Math.PI/180,lo=((ra-gm+Math.PI*3)%(2*Math.PI))-Math.PI;return new T.Vector3(Math.cos(dec)*Math.cos(lo),Math.sin(dec),-Math.cos(dec)*Math.sin(lo)).normalize()}
function setSun(d){sunDir.copy(sunHelper?sunHelper(d):sf(d)).normalize();sl.position.copy(sunDir).multiplyScalar(10)}
window.setCinematicISS=(la,lo,alt)=>{const p=xyz(la,lo,1+Math.max(alt,0)/6378.137);iss.position.copy(p);halo.position.copy(p);if(follow){cam.position.copy(p.clone().normalize().multiplyScalar(2.35));cam.lookAt(earth.position)}};
window.setCinematicOrbit=(sat,d)=>{if(!sat)return;const pts=[];for(let m=-50;m<=50;m++){const t=new Date(d.getTime()+m*60000),pv=satellite.propagate(sat,t);if(!pv.position)continue;const g=satellite.eciToGeodetic(pv.position,satellite.gstime(t));pts.push(xyz(satellite.degreesLat(g.latitude),satellite.degreesLong(g.longitude),1.018).add(new T.Vector3(0,-.06,0)))}orbit.geometry.dispose();orbit.geometry=new T.BufferGeometry().setFromPoints(pts)};window.updateISS3D=window.setCinematicISS;window.updateOrbitPath=window.setCinematicOrbit;
canvas.addEventListener('pointerdown',e=>{drag=true;x0=e.clientX;y0=e.clientY});addEventListener('pointerup',()=>drag=false);addEventListener('pointermove',e=>{if(!drag)return;rig.rotation.y+=(e.clientX-x0)*.0035;rig.rotation.x=Math.max(-.65,Math.min(.65,rig.rotation.x+(e.clientY-y0)*.002));x0=e.clientX;y0=e.clientY});canvas.addEventListener('wheel',e=>zoom=Math.max(2.2,Math.min(4.7,zoom+(e.deltaY>0?.1:-.1))),{passive:true});
window.toggleEarthAuto=()=>auto=!auto;window.toggleEarthFollow=()=>follow=!follow;window.resetEarth=()=>{rig.rotation.set(0,0,0);cam.position.set(0,.02,3.05);zoom=3.05;follow=false};cam.position.set(0,.02,3.05);
function loop(t){requestAnimationFrame(loop);if(auto&&!drag&&!follow){rig.rotation.y+=.0001;cam.position.x=Math.sin(t*.00003)*.045;cam.position.y=.02+Math.sin(t*.00002)*.015;cam.lookAt(earth.position)}earth.rotation.y+=.00001;clouds.rotation.y+=.00006;cm.uniforms.time.value=t;cam.position.z+=(zoom-cam.position.z)*.04;setSun(new Date());r.render(s,cam)}requestAnimationFrame(loop);addEventListener('resize',()=>{cam.aspect=innerWidth/innerHeight;cam.updateProjectionMatrix();r.setSize(innerWidth,innerHeight)});
})();
