// Realistic cinematic Earth: NASA Blue Marble + custom day/night, city lights, moving clouds, subtle atmosphere, ISS SGP4 overlays.
(async()=>{
const T=await import('https://esm.sh/three@0.180.0');
let sunHelper=null;try{sunHelper=(await import('https://esm.sh/@takram/three-atmosphere@0.19.1?deps=three@0.180.0')).getSunDirectionECEF}catch(e){}
const canvas=document.getElementById('earth3d'),r=new T.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});r.setPixelRatio(Math.min(devicePixelRatio,2));r.setSize(innerWidth,innerHeight);r.outputColorSpace=T.SRGBColorSpace;r.toneMapping=T.ACESFilmicToneMapping;r.toneMappingExposure=1.12;
const s=new T.Scene();s.background=new T.Color(0x02070d);const cam=new T.PerspectiveCamera(38,innerWidth/innerHeight,.01,1000);const rig=new T.Group();s.add(rig);
const sg=new T.BufferGeometry(),a=[];for(let i=0;i<2200;i++){const R=65,u=Math.random()*2-1,q=Math.sqrt(1-u*u),p=Math.random()*Math.PI*2;a.push(R*q*Math.cos(p),R*u,R*q*Math.sin(p))}sg.setAttribute('position',new T.Float32BufferAttribute(a,3));s.add(new T.Points(sg,new T.PointsMaterial({color:0xdff7ff,size:.055,sizeAttenuation:true,transparent:true,opacity:.7})));
const L=new T.TextureLoader(),earthTex=L.load('https://svs.gsfc.nasa.gov/vis/a000000/a002900/a002915/bluemarble-2048.png'),normal=L.load('https://threejs.org/examples/textures/planets/earth_normal_2048.jpg'),spec=L.load('https://threejs.org/examples/textures/planets/earth_specular_2048.jpg'),lights=L.load('https://threejs.org/examples/textures/planets/earth_lights_2048.png'),cloudTex=L.load('https://threejs.org/examples/textures/planets/earth_clouds_2048.png');[earthTex,lights,cloudTex].forEach(x=>x.colorSpace=T.SRGBColorSpace);
const sunDir=new T.Vector3(.7,.3,.6).normalize(),E=new T.SphereGeometry(1,192,128);
const em=new T.ShaderMaterial({uniforms:{map:{value:earthTex},normal:{value:normal},spec:{value:spec},lights:{value:lights},sunDir:{value:sunDir}},vertexShader:`varying vec2 uv;varying vec3 nW,pW;void main(){uv=uv;nW=normalize(mat3(modelMatrix)*normal);vec4 p=modelMatrix*vec4(position,1.);pW=p.xyz;gl_Position=projectionMatrix*viewMatrix*p;}`,fragmentShader:`uniform sampler2D map,normal,lights,spec;uniform vec3 sunDir;varying vec2 uv;varying vec3 nW,pW;void main(){vec3 n=normalize(nW),v=normalize(cameraPosition-pW),base=texture2D(map,uv).rgb;float d=dot(n,sunDir),day=smoothstep(-.04,.18,d),night=1.-day;vec3 city=texture2D(lights,uv).rgb*night*1.08;float sp=texture2D(spec,uv).r;vec3 h=normalize(sunDir+v);float hi=pow(max(dot(n,h),0.),55.)*sp*.12*max(d,0.);float rim=pow(1.-max(dot(n,v),0.),3.8);vec3 c=base*(.32+.82*day)+city+vec3(hi)+vec3(.03,.16,.55)*rim*.08;gl_FragColor=vec4(c,1.);}`});
const earth=new T.Mesh(E,em);earth.position.y=-.08;rig.add(earth);
const cm=new T.ShaderMaterial({transparent:true,depthWrite:false,side:T.DoubleSide,uniforms:{map:{value:cloudTex},sunDir:{value:sunDir},time:{value:0}},vertexShader:`varying vec2 uv;varying vec3 nW;void main(){uv=uv;nW=normalize(mat3(modelMatrix)*normal);gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`,fragmentShader:`uniform sampler2D map;uniform vec3 sunDir;uniform float time;varying vec2 uv;varying vec3 nW;void main(){vec4 c=texture2D(map,uv+vec2(time*.00016,0.));float l=max(dot(normalize(nW),normalize(sunDir)),0.);float al=smoothstep(.02,.25,c.a)*(.08+.48*l);gl_FragColor=vec4(1.,1.,1.,al);}`});const clouds=new T.Mesh(new T.SphereGeometry(1.014,160,112),cm);clouds.position.y=-.08;rig.add(clouds);
const am=new T.ShaderMaterial({transparent:true,side:T.BackSide,depthWrite:false,blending:T.AdditiveBlending,vertexShader:`varying vec3 n,v;void main(){n=normalize(mat3(modelMatrix)*normal);vec4 p=modelMatrix*vec4(position,1.);v=normalize(cameraPosition-p.xyz);gl_Position=projectionMatrix*viewMatrix*p;}`,fragmentShader:`varying vec3 n,v;void main(){float rim=pow(1.-max(dot(n,v),0.),5.);gl_FragColor=vec4(.12,.52,1.,rim*.14);}`});const atmo=new T.Mesh(new T.SphereGeometry(1.035,144,96),am);atmo.position.y=-.08;rig.add(atmo);
const orbit=new T.Line(new T.BufferGeometry(),new T.LineBasicMaterial({color:0x65eaff,transparent:true,opacity:.22}));rig.add(orbit);const iss=new T.Mesh(new T.SphereGeometry(.018,16,16),new T.MeshBasicMaterial({color:0x7af0ff}));rig.add(iss);const halo=new T.Sprite(new T.SpriteMaterial({color:0x7af0ff,transparent:true,opacity:.8,blending:T.AdditiveBlending}));halo.scale.set(.085,.085,1);rig.add(halo);
const sl=new T.DirectionalLight(0xffffff,2.15);s.add(sl);s.add(new T.AmbientLight(0x5c7180,.46));let auto=true,follow=false,drag=false,x0=0,y0=0,zoom=3.05;
const xyz=(la,lo,rr=1)=>{la*=Math.PI/180;lo*=Math.PI/180;return new T.Vector3(rr*Math.cos(la)*Math.cos(lo),rr*Math.sin(la),-rr*Math.cos(la)*Math.sin(lo))};
function sf(d){const jd=d.getTime()/864e5+2440587.5,n=jd-2451545,L=(280.46+.9856474*n)*Math.PI/180,g=(357.53+.9856*n)*Math.PI/180,lam=L+(1.915*Math.sin(g)+.02*Math.sin(2*g))*Math.PI/180,e=(23.439-.0000004*n)*Math.PI/180,ra=Math.atan2(Math.cos(e)*Math.sin(lam),Math.cos(lam)),dec=Math.asin(Math.sin(e)*Math.sin(lam)),gm=(280.46061837+360.98564736629*n)*Math.PI/180,lo=((ra-gm+Math.PI*3)%(2*Math.PI))-Math.PI;return new T.Vector3(Math.cos(dec)*Math.cos(lo),Math.sin(dec),-Math.cos(dec)*Math.sin(lo)).normalize()}
function setSun(d){sunDir.copy(sunHelper?sunHelper(d):sf(d)).normalize();sl.position.copy(sunDir).multiplyScalar(10)}
window.setCinematicISS=(la,lo,alt)=>{const p=xyz(la,lo,1+Math.max(alt,0)/6378.137);iss.position.copy(p);halo.position.copy(p);if(follow){cam.position.copy(p.clone().normalize().multiplyScalar(2.2));cam.lookAt(earth.position)}};
window.setCinematicOrbit=(sat,d)=>{if(!sat)return;const pts=[];for(let m=-50;m<=50;m++){const t=new Date(d.getTime()+m*60000),pv=satellite.propagate(sat,t);if(!pv.position)continue;const g=satellite.eciToGeodetic(pv.position,satellite.gstime(t));pts.push(xyz(satellite.degreesLat(g.latitude),satellite.degreesLong(g.longitude),1.02).add(new T.Vector3(0,-.08,0)))}orbit.geometry.dispose();orbit.geometry=new T.BufferGeometry().setFromPoints(pts)};window.updateISS3D=window.setCinematicISS;window.updateOrbitPath=window.setCinematicOrbit;
canvas.addEventListener('pointerdown',e=>{drag=true;x0=e.clientX;y0=e.clientY});addEventListener('pointerup',()=>drag=false);addEventListener('pointermove',e=>{if(!drag)return;rig.rotation.y+=(e.clientX-x0)*.0035;rig.rotation.x=Math.max(-.65,Math.min(.65,rig.rotation.x+(e.clientY-y0)*.002));x0=e.clientX;y0=e.clientY});canvas.addEventListener('wheel',e=>zoom=Math.max(2.2,Math.min(4.7,zoom+(e.deltaY>0?.1:-.1))),{passive:true});
window.toggleEarthAuto=()=>auto=!auto;window.toggleEarthFollow=()=>follow=!follow;window.resetEarth=()=>{rig.rotation.set(0,0,0);cam.position.set(0,.02,3.05);zoom=3.05;follow=false};cam.position.set(0,.02,3.05);
function loop(t){requestAnimationFrame(loop);if(auto&&!drag&&!follow){rig.rotation.y+=.0001;cam.position.x=Math.sin(t*.00003)*.045;cam.position.y=.02+Math.sin(t*.00002)*.015;cam.lookAt(earth.position)}earth.rotation.y+=.000014;clouds.rotation.y+=.00008;cm.uniforms.time.value=t;cam.position.z+=(zoom-cam.position.z)*.04;setSun(new Date());r.render(s,cam)}requestAnimationFrame(loop);addEventListener('resize',()=>{cam.aspect=innerWidth/innerHeight;cam.updateProjectionMatrix();r.setSize(innerWidth,innerHeight)});
})();
