// Cinematic Earth renderer: Three.js + Takram atmosphere helper + custom shaders.
(async()=>{
  const THREE=await import('https://esm.sh/three@0.180.0');
  let getSunDirectionECEF=null;
  try{({getSunDirectionECEF}=await import('https://esm.sh/@takram/three-atmosphere@0.19.1?deps=three@0.180.0'))}catch(e){console.warn('Takram atmosphere helper unavailable; using fallback sun model.',e)}
  const canvas=document.getElementById('earth3d');
  const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});
  renderer.setPixelRatio(Math.min(devicePixelRatio,2)); renderer.setSize(innerWidth,innerHeight); renderer.outputColorSpace=THREE.SRGBColorSpace; renderer.toneMapping=THREE.ACESFilmicToneMapping; renderer.toneMappingExposure=1.1;
  const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(36,innerWidth/innerHeight,.01,1000),rig=new THREE.Group();scene.add(rig);
  const starsGeo=new THREE.BufferGeometry(),sv=[];for(let i=0;i<1500;i++){const r=55,u=Math.random()*2-1,a=Math.random()*Math.PI*2,s=Math.sqrt(1-u*u);sv.push(r*s*Math.cos(a),r*u,r*s*Math.sin(a))}starsGeo.setAttribute('position',new THREE.Float32BufferAttribute(sv,3));scene.add(new THREE.Points(starsGeo,new THREE.PointsMaterial({color:0xeaf9ff,size:.08,sizeAttenuation:true,transparent:true,opacity:.72})));
  const loader=new THREE.TextureLoader();const earthTex=loader.load('https://threejs.org/examples/textures/planets/earth_atmos_2048.jpg'),normalTex=loader.load('https://threejs.org/examples/textures/planets/earth_normal_2048.jpg'),specTex=loader.load('https://threejs.org/examples/textures/planets/earth_specular_2048.jpg'),cityTex=loader.load('https://threejs.org/examples/textures/planets/earth_lights_2048.png'),cloudTex=loader.load('https://threejs.org/examples/textures/planets/earth_clouds_2048.png');
  [earthTex,normalTex,specTex,cityTex,cloudTex].forEach(t=>{t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=renderer.capabilities.getMaxAnisotropy()});
  const E=new THREE.SphereGeometry(1,192,128),sunDir=new THREE.Vector3(5,2,5).normalize();
  const mat=new THREE.ShaderMaterial({uniforms:{map:{value:earthTex},normalMap:{value:normalTex},specMap:{value:specTex},lights:{value:cityTex},sunDir:{value:sunDir}},vertexShader:`varying vec2 vUv;varying vec3 vNormalW;varying vec3 vPosW;void main(){vUv=uv;vNormalW=normalize(mat3(modelMatrix)*normal);vec4 p=modelMatrix*vec4(position,1.0);vPosW=p.xyz;gl_Position=projectionMatrix*viewMatrix*p;}`,fragmentShader:`uniform sampler2D map,normalMap,specMap,lights;uniform vec3 sunDir;varying vec2 vUv;varying vec3 vNormalW;varying vec3 vPosW;void main(){vec3 base=texture2D(map,vUv).rgb;vec3 n=normalize(vNormalW);float ndl=max(dot(n,sunDir),0.0);float night=smoothstep(.22,.02,ndl);vec3 city=texture2D(lights,vUv).rgb*night*1.5;float spec=texture2D(specMap,vUv).r;vec3 viewDir=normalize(cameraPosition-vPosW);vec3 h=normalize(sunDir+viewDir);float specHit=pow(max(dot(n,h),0.0),48.0)*spec*.22*ndl;vec3 c=base*(.16+.98*ndl)+city+vec3(specHit);float limb=pow(1.0-max(dot(n,viewDir),0.0),3.4);c+=vec3(.08,.42,1.0)*limb*.28;gl_FragColor=vec4(c,1.0);}`});
  const earth=new THREE.Mesh(E,mat);rig.add(earth);
  const cloudMat=new THREE.ShaderMaterial({transparent:true,depthWrite:false,side:THREE.DoubleSide,uniforms:{clouds:{value:cloudTex},time:{value:0},sunDir:{value:sunDir}},vertexShader:`varying vec2 vUv;varying vec3 nW;void main(){vUv=uv;nW=normalize(mat3(modelMatrix)*normal);gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}`,fragmentShader:`uniform sampler2D clouds;uniform float time;uniform vec3 sunDir;varying vec2 vUv;varying vec3 nW;void main(){vec2 uv=vUv+vec2(time*.0013,0.0);vec4 c=texture2D(clouds,uv);float light=max(dot(normalize(nW),normalize(sunDir)),0.0);float a=c.a*.46*(.22+.78*light);gl_FragColor=vec4(vec3(.98,.995,1.0)*(.7+.3*light),a);}`});rig.add(new THREE.Mesh(new THREE.SphereGeometry(1.012,160,112),cloudMat));
  const atmoMat=new THREE.ShaderMaterial({transparent:true,side:THREE.BackSide,depthWrite:false,blending:THREE.AdditiveBlending,uniforms:{sunDir:{value:sunDir}},vertexShader:`varying vec3 vN;varying vec3 vV;void main(){vN=normalize(mat3(modelMatrix)*normal);vec4 p=modelMatrix*vec4(position,1.0);vV=normalize(cameraPosition-p.xyz);gl_Position=projectionMatrix*viewMatrix*p;}`,fragmentShader:`varying vec3 vN;varying vec3 vV;void main(){float edge=1.0-max(dot(vN,vV),0.0);float glow=pow(edge,3.2);gl_FragColor=vec4(.08,.48,1.0,glow*.78);}`});rig.add(new THREE.Mesh(new THREE.SphereGeometry(1.075,128,96),atmoMat));
  const orbit=new THREE.Line(new THREE.BufferGeometry(),new THREE.LineBasicMaterial({color:0x61e8ff,transparent:true,opacity:.3}));rig.add(orbit);const iss=new THREE.Mesh(new THREE.SphereGeometry(.022,20,20),new THREE.MeshBasicMaterial({color:0x69efff}));rig.add(iss);const issHalo=new THREE.Sprite(new THREE.SpriteMaterial({color:0x69efff,transparent:true,opacity:.9,blending:THREE.AdditiveBlending}));issHalo.scale.set(.12,.12,1);rig.add(issHalo);
  const sunLight=new THREE.DirectionalLight(0xffffff,2.7);scene.add(sunLight);scene.add(new THREE.AmbientLight(0x35526a,.28));let auto=true,follow=false,drag=false,px=0,py=0,zoom=2.7;
  const toXYZ=(lat,lon,r=1)=>{const la=lat*Math.PI/180,lo=lon*Math.PI/180;return new THREE.Vector3(r*Math.cos(la)*Math.cos(lo),r*Math.sin(la),-r*Math.cos(la)*Math.sin(lo))};
  const setSun=d=>{let v;if(getSunDirectionECEF)v=getSunDirectionECEF(d);else{const jd=d.getTime()/86400000+2440587.5,n=jd-2451545,L=(280.46+.9856474*n)*Math.PI/180,g=(357.53+.9856*n)*Math.PI/180,lam=L+(1.915*Math.sin(g)+.02*Math.sin(2*g))*Math.PI/180,eps=(23.439-.0000004*n)*Math.PI/180,ra=Math.atan2(Math.cos(eps)*Math.sin(lam),Math.cos(lam)),dec=Math.asin(Math.sin(eps)*Math.sin(lam)),gm=(280.46061837+360.98564736629*n)*Math.PI/180;let lo=ra-gm;lo=((lo+Math.PI*3)%(Math.PI*2))-Math.PI;v=new THREE.Vector3(Math.cos(dec)*Math.cos(lo),Math.sin(dec),-Math.cos(dec)*Math.sin(lo))}sunDir.copy(v).normalize();sunLight.position.copy(sunDir).multiplyScalar(10)};
  window.setCinematicISS=(lat,lon,alt)=>{const p=toXYZ(lat,lon,1+alt/6378.137);iss.position.copy(p);issHalo.position.copy(p);if(follow){camera.position.copy(p.clone().normalize().multiplyScalar(2.1));camera.lookAt(0,0,0)}};
  window.setCinematicOrbit=(sat,d)=>{if(!sat)return;const pts=[];for(let m=-45;m<=45;m++){const t=new Date(d.getTime()+m*60000),pv=satellite.propagate(sat,t);if(!pv.position)continue;const g=satellite.eciToGeodetic(pv.position,satellite.gstime(t));pts.push(toXYZ(satellite.degreesLat(g.latitude),satellite.degreesLong(g.longitude),1.02))}orbit.geometry.dispose();orbit.geometry=new THREE.BufferGeometry().setFromPoints(pts)};
  window.updateISS3D=window.setCinematicISS;window.updateOrbitPath=(sat,d)=>window.setCinematicOrbit(sat,d);
  canvas.addEventListener('pointerdown',e=>{drag=true;px=e.clientX;py=e.clientY});addEventListener('pointerup',()=>drag=false);addEventListener('pointermove',e=>{if(!drag)return;rig.rotation.y+=(e.clientX-px)*.004;rig.rotation.x=Math.max(-1.05,Math.min(1.05,rig.rotation.x+(e.clientY-py)*.0025));px=e.clientX;py=e.clientY});canvas.addEventListener('wheel',e=>{zoom=Math.max(1.75,Math.min(5,zoom+(e.deltaY>0?.12:-.12)))},{passive:true});
  window.toggleEarthAuto=()=>auto=!auto;window.resetEarth=()=>{rig.rotation.set(0,0,0);zoom=2.7;follow=false};window.toggleEarthFollow=()=>follow=!follow;
  function frame(t){requestAnimationFrame(frame);if(auto&&!drag&&!follow)rig.rotation.y+=.00022;earth.rotation.y+=.000045;cloudMat.uniforms.time.value=t*.015;camera.position.z+=(zoom-camera.position.z)*.06;setSun(new Date());renderer.render(scene,camera)}requestAnimationFrame(frame);addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
})();
