/* GPM Core Observatory mode: real orbital propagation + NASA GIBS IMERG precipitation overlay. */
(() => {
  const Cesium=window.Cesium, viewer=window.CesiumEarthViewer, satellite=window.satellite;
  if(!Cesium||!viewer||!satellite)return;
  const FILE='data/missions.tle', WMS='https://gibs.earthdata.nasa.gov/wms/epsg4326/best/wms.cgi', WORLD=Cesium.Rectangle.fromDegrees(-180,-90,180,90);
  let satrec=null,precipLayer=null,active=false,lastDate='';
  const status=document.createElement('div');status.style.cssText='position:fixed;left:50%;bottom:118px;transform:translateX(-50%);z-index:40;padding:7px 11px;border:1px solid rgba(255,79,216,.3);border-radius:4px;background:rgba(14,5,15,.9);color:#ff9ce9;font:700 7px ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.1em;display:none;pointer-events:none;backdrop-filter:blur(10px)';document.body.appendChild(status);const setStatus=t=>{status.textContent=t;status.style.display=t?'block':'none'};
  const gpm=viewer.entities.add({id:'GPM-39574-CINEMATIC',name:'GPM Core Observatory · 39574',position:Cesium.Cartesian3.fromDegrees(0,0,440000),point:{pixelSize:11,color:Cesium.Color.fromCssColorString('#ff4fd8'),outlineColor:Cesium.Color.WHITE,outlineWidth:2,disableDepthTestDistance:Number.POSITIVE_INFINITY},label:{text:'GPM · 39574',font:'900 10px monospace',fillColor:Cesium.Color.fromCssColorString('#ff8fe4'),outlineColor:Cesium.Color.BLACK,outlineWidth:3,verticalOrigin:Cesium.VerticalOrigin.BOTTOM,pixelOffset:new Cesium.Cartesian2(0,-15),disableDepthTestDistance:Number.POSITIVE_INFINITY,showBackground:true,backgroundColor:new Cesium.Color(.07,.01,.07,.86),backgroundPadding:new Cesium.Cartesian2(5,3)}});
  const orbit=viewer.entities.add({id:'GPM-ORBIT-CINEMATIC',polyline:{positions:[],width:2.4,material:new Cesium.PolylineGlowMaterialProperty({glowPower:.2,taperPower:.45,color:Cesium.Color.fromCssColorString('#ff4fd8').withAlpha(.7)}),arcType:Cesium.ArcType.NONE}});
  const ground=viewer.entities.add({id:'GPM-GROUND-CINEMATIC',polyline:{positions:[],width:1.8,material:new Cesium.PolylineGlowMaterialProperty({glowPower:.15,taperPower:.5,color:Cesium.Color.fromCssColorString('#ff9ae9').withAlpha(.42)}),clampToGround:true,arcType:Cesium.ArcType.GEODESIC}});
  const swath=viewer.entities.add({id:'GPM-SWATH-CINEMATIC',corridor:{positions:[],width:360000,material:new Cesium.ColorMaterialProperty(Cesium.Color.fromCssColorString('#ff4fd8').withAlpha(.08)),outline:true,outlineColor:Cesium.Color.fromCssColorString('#ff4fd8').withAlpha(.42),height:100}});
  function parseTLE(text){const l=text.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);for(let i=0;i<l.length-2;i++){if(/GPM/i.test(l[i])&&/^1\s+39574\s/.test(l[i+1])&&/^2\s+39574\s/.test(l[i+2]))return[l[i+1],l[i+2]];if(/^1\s+39574\s/.test(l[i])&&/^2\s+39574\s/.test(l[i+1]))return[l[i],l[i+1]]}throw Error('GPM TLE not found')}
  const prop=d=>{if(!satrec)return null;const p=satellite.propagate(satrec,d);if(!p?.position)return null;const geo=satellite.eciToGeodetic(p.position,satellite.gstime(d));return{lat:satellite.degreesLat(geo.latitude),lon:satellite.degreesLong(geo.longitude),alt:Math.max(geo.height,0),speed:p.velocity?Math.hypot(p.velocity.x,p.velocity.y,p.velocity.z)*3600:0}};
  const refresh=d=>{const o=[],g=[];for(let m=-48;m<=48;m++){const a=prop(new Date(d.getTime()+m*60000));if(!a)continue;o.push(Cesium.Cartesian3.fromDegrees(a.lon,a.lat,a.alt*1000+16000));g.push(Cesium.Cartesian3.fromDegrees(a.lon,a.lat,0))}orbit.polyline.positions=o;ground.polyline.positions=g;swath.corridor.positions=g};
  async function load(){try{const r=await fetch(FILE,{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);const[l1,l2]=parseTLE(await r.text());satrec=satellite.twoline2satrec(l1,l2);refresh(new Date());tick()}catch(e){console.warn('GPM orbital cache unavailable',e)}}
  async function precipitation(){const d=new Date();d.setUTCMinutes(Math.floor(d.getUTCMinutes()/30)*30,0,0);const date=d.toISOString().slice(0,16);if(date===lastDate&&precipLayer)return;const p=new URLSearchParams({service:'WMS',version:'1.1.1',request:'GetMap',layers:'IMERG_Precipitation_Rate',styles:'',srs:'EPSG:4326',bbox:'-180,-90,180,90',width:'2048',height:'1024',format:'image/png',transparent:'true',time:date});const provider=await Cesium.SingleTileImageryProvider.fromUrl(`${WMS}?${p.toString()}`,{rectangle:WORLD,credit:'NASA GIBS · IMERG'});const layer=new Cesium.ImageryLayer(provider,{alpha:.68,show:true});if(precipLayer)viewer.imageryLayers.remove(precipLayer,true);precipLayer=viewer.imageryLayers.add(layer,0);lastDate=date}
  function tick(){const a=prop(new Date());if(!a)return;gpm.position=Cesium.Cartesian3.fromDegrees(a.lon,a.lat,a.alt*1000);window.GPMTelemetry={altitudeKm:a.alt,speedKmh:a.speed,latitude:a.lat,longitude:a.lon};const label=document.querySelector('[data-key="GPM"] .mission-state');if(label)label.textContent='GPM TRACKING';if(active)viewer.camera.lookAt(Cesium.Cartesian3.fromDegrees(a.lon,a.lat,0),new Cesium.HeadingPitchRange(Cesium.Math.toRadians(18),Cesium.Math.toRadians(-44),2500000))}
  async function focus(){if(active){active=false;if(precipLayer){viewer.imageryLayers.remove(precipLayer,true);precipLayer=null;lastDate=''}setStatus('');const b=document.getElementById('gpmFocus');if(b){b.classList.remove('on');b.textContent='FOCUS GPM + PRECIPITATION'}return}active=true;setStatus('GPM CORE · IMERG PRECIPITATION · ORBITAL CAMERA');try{await precipitation()}catch(e){console.warn('GPM precipitation unavailable',e);setStatus('GPM CORE · ORBIT LIVE · PRECIPITATION UNAVAILABLE')}const a=prop(new Date());if(a)viewer.camera.flyTo({destination:Cesium.Cartesian3.fromDegrees(a.lon,a.lat,a.alt*1000+2500000),orientation:{heading:Cesium.Math.toRadians(18),pitch:Cesium.Math.toRadians(-44),roll:0},duration:2.8});const b=document.getElementById('gpmFocus');if(b){b.classList.add('on');b.textContent='EXIT GPM MODE'}}
  window.GPMMode={focus,load,tick,get active(){return active}};load();setInterval(tick,1000);setInterval(()=>{if(active)precipitation().catch(()=>{})},5*60*1000);
})();
