/* Multi-satellite Earth-observation visualization for the cinematic globe. */
(() => {
  const Cesium = window.Cesium;
  const viewer = window.CesiumEarthViewer;
  const satellite = window.satellite;
  if (!Cesium || !viewer || !satellite) return;

  const FILE='data/missions.tle';
  const defs=[
    {key:'TERRA',label:'TERRA',color:Cesium.Color.ORANGE},
    {key:'AQUA',label:'AQUA',color:Cesium.Color.fromCssColorString('#7BE7FF')},
    {key:'LANDSAT 9',label:'LANDSAT 9',color:Cesium.Color.LIME},
    {key:'SENTINEL-1A',label:'SENTINEL-1A',color:Cesium.Color.MAGENTA},
    {key:'GPM',label:'GPM · PRECIPITATION',color:Cesium.Color.fromCssColorString('#ff4fd8'),norad:'39574',swath:true}
  ];
  const assets=new Map(); let sats=[];

  const css=document.createElement('style');
  css.textContent=`.mission-panel{position:fixed;right:18px;bottom:122px;z-index:27;width:282px;border:1px solid rgba(255,255,255,.11);border-radius:7px;background:rgba(3,10,16,.86);backdrop-filter:blur(14px);box-shadow:0 16px 45px #0008;font:8px ui-monospace,SFMono-Regular,Menlo,monospace;color:#dce7eb;letter-spacing:.08em}.mission-head{padding:9px 11px;border-bottom:1px solid rgba(255,255,255,.1);display:flex;justify-content:space-between;font-weight:900}.mission-head span:last-child{color:#5ef0a6;font-size:7px}.mission-row{display:flex;align-items:center;gap:8px;padding:7px 10px;border-bottom:1px solid rgba(255,255,255,.06);cursor:pointer}.mission-row:hover{background:rgba(116,237,255,.05)}.mission-dot{width:7px;height:7px;border-radius:50%;box-shadow:0 0 9px currentColor}.mission-name{flex:1}.mission-state{font-size:7px;color:#8796a0}.mission-row.featured{background:linear-gradient(90deg,rgba(255,79,216,.08),transparent)}.mission-row.featured .mission-name{color:#ffd5f6}.mission-foot{padding:7px 10px;color:#82919a;font-size:7px;line-height:1.45}.gpm-callout{margin:8px 10px;padding:8px 9px;border:1px solid rgba(255,79,216,.26);border-radius:5px;background:linear-gradient(135deg,rgba(255,79,216,.10),rgba(116,237,255,.04));color:#cdbdcc}.gpm-callout b{display:block;color:#ff8fe5;font-size:9px;margin-bottom:4px}.gpm-callout span{font-size:7px;line-height:1.45;display:block}.gpm-focus{margin-top:7px;appearance:none;border:1px solid rgba(255,79,216,.35);background:rgba(255,79,216,.08);color:#ff9ce9;border-radius:4px;padding:6px 8px;font:800 7px ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.1em;cursor:pointer}.gpm-focus:hover{background:rgba(255,79,216,.14)}@media(max-width:900px){.mission-panel{right:10px;bottom:110px;width:242px}}@media(max-width:620px){.mission-panel{right:10px;bottom:95px;width:185px}.mission-row{padding:6px 8px}.mission-foot,.gpm-callout{display:none}}`;
  document.head.appendChild(css);

  const panel=document.createElement('section'); panel.className='mission-panel';
  panel.innerHTML='<div class="mission-head"><span>EARTH-OBSERVING FLEET</span><span id="fleetState">SYNCING</span></div><div id="fleetRows"></div><div class="gpm-callout"><b>GPM · GLOBAL PRECIPITATION MEASUREMENT</b><span>NASA/JAXA precipitation mission · NORAD 39574 · orbital footprint visualization.</span><button type="button" class="gpm-focus" id="gpmFocus">FOCUS GPM + PRECIPITATION</button></div><div class="mission-foot">ISS + NASA EARTH MISSIONS · SGP4</div>';
  document.body.appendChild(panel);
  const rows=panel.querySelector('#fleetRows');
  for(const d of defs){const row=document.createElement('div');row.className='mission-row'+(d.swath?' featured':'');row.dataset.key=d.key;row.innerHTML=`<span class="mission-dot" style="color:${d.color.toCssColorString()};background:${d.color.toCssColorString()}"></span><span class="mission-name">${d.label}</span><span class="mission-state">WAITING</span>`;rows.appendChild(row)}

  function parse(text){const lines=text.split(/\r?\n/).map(s=>s.trim()).filter(Boolean),out=[];for(let i=0;i<lines.length;){if(lines[i].startsWith('1 ')&&lines[i+1]?.startsWith('2 ')){out.push({name:'UNKNOWN',l1:lines[i],l2:lines[i+1]});i+=2}else if(lines[i+1]?.startsWith('1 ')&&lines[i+2]?.startsWith('2 ')){out.push({name:lines[i],l1:lines[i+1],l2:lines[i+2]});i+=3}else i++}return out}
  function match(name,rec){const n=(name||'').toUpperCase();for(const d of defs)if(n.includes(d.key))return d;const id=String(rec.satnum||'');if(id==='25994')return defs[0];if(id==='27424')return defs[1];if(id==='49260')return defs[2];if(id==='39634')return defs[3];if(id==='39574')return defs[4];return null}
  function focusGPM(){const s=sats.find(x=>x.def.key==='GPM'),a=assets.get('GPM');if(!s||!a){console.warn('GPM position not ready');return}try{const now=new Date(),p=satellite.propagate(s.rec,now);const g=satellite.eciToGeodetic(p.position,satellite.gstime(now));const lat=satellite.degreesLat(g.latitude),lon=satellite.degreesLong(g.longitude),alt=Math.max(g.height,0)*1000;viewer.camera.flyTo({destination:Cesium.Cartesian3.fromDegrees(lon,lat,alt+1400000),orientation:{heading:Cesium.Math.toRadians(12),pitch:Cesium.Math.toRadians(-58),roll:0},duration:2.8});window.GPMMode?.focus();}catch(e){console.warn('GPM focus failed',e)}}
  panel.querySelector('#gpmFocus').addEventListener('click',focusGPM);
  rows.querySelector('[data-key="GPM"]')?.addEventListener('click',focusGPM);

  async function load(){try{const r=await fetch(FILE,{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);const text=await r.text();sats=parse(text).map(x=>{try{const rec=satellite.twoline2satrec(x.l1,x.l2),def=match(x.name,rec);return def?{...x,rec,def}:null}catch{return null}}).filter(Boolean);panel.querySelector('#fleetState').textContent=`${sats.length} ACTIVE`;for(const d of defs){const row=rows.querySelector(`[data-key="${d.key}"] .mission-state`);if(row)row.textContent=sats.some(s=>s.def.key===d.key)?(d.swath?'GPM TRACKING':'TRACKING'):'NO TLE'}for(const s of sats)if(!assets.has(s.def.key)){const entity=viewer.entities.add({id:'SAT-'+s.def.key,name:s.def.label,position:Cesium.Cartesian3.fromDegrees(0,0,700000),point:{pixelSize:s.def.swath?10:7,color:s.def.color,outlineColor:Cesium.Color.BLACK,outlineWidth:2,disableDepthTestDistance:Number.POSITIVE_INFINITY},label:{text:s.def.label,font:'700 9px monospace',fillColor:s.def.color,outlineColor:Cesium.Color.BLACK,outlineWidth:3,style:Cesium.LabelStyle.FILL_AND_OUTLINE,verticalOrigin:Cesium.VerticalOrigin.BOTTOM,pixelOffset:new Cesium.Cartesian2(0,-10),disableDepthTestDistance:Number.POSITIVE_INFINITY,showBackground:true,backgroundColor:new Cesium.Color(.02,.06,.09,.65),backgroundPadding:new Cesium.Cartesian2(4,3)}});const path=viewer.entities.add({id:'PATH-'+s.def.key,polyline:{positions:[],width:s.def.swath?2.4:1.1,material:new Cesium.PolylineGlowMaterialProperty({glowPower:s.def.swath?.24:.13,color:s.def.color.withAlpha(s.def.swath?.58:.32)}),arcType:Cesium.ArcType.NONE}});const swath=s.def.swath?viewer.entities.add({id:'SWATH-'+s.def.key,corridor:{positions:[],width:520000,material:new Cesium.ColorMaterialProperty(s.def.color.withAlpha(.08)),outline:true,outlineColor:s.def.color.withAlpha(.45),height:0}}):null;assets.set(s.def.key,{entity,path,swath})}}catch(e){panel.querySelector('#fleetState').textContent='OFFLINE';console.warn('Mission TLE cache unavailable',e)}}
  function tick(){const now=new Date();for(const s of sats){try{const pv=satellite.propagate(s.rec,now);if(!pv.position)continue;const g=satellite.eciToGeodetic(pv.position,satellite.gstime(now));const lat=satellite.degreesLat(g.latitude),lon=satellite.degreesLong(g.longitude),alt=Math.max(g.height,0)*1000,a=assets.get(s.def.key);if(!a)continue;a.entity.position=Cesium.Cartesian3.fromDegrees(lon,lat,alt);const pts=[],ground=[];for(let m=-25;m<=25;m+=2){const t=new Date(now.getTime()+m*60000),pp=satellite.propagate(s.rec,t);if(!pp.position)continue;const gg=satellite.eciToGeodetic(pp.position,satellite.gstime(t));const glon=satellite.degreesLong(gg.longitude),glat=satellite.degreesLat(gg.latitude);pts.push(Cesium.Cartesian3.fromDegrees(glon,glat,Math.max(gg.height,0)*1000+14000));ground.push(Cesium.Cartesian3.fromDegrees(glon,glat,0))}a.path.polyline.positions=pts;if(a.swath)a.swath.corridor.positions=ground}catch{}}}
  window.EarthMissionFleet={load,tick,getCount:()=>sats.length,focusGPM};load();setInterval(load,30*60*1000);setInterval(tick,5000);
})();